<a href="https://colab.research.google.com/github/Tech-Amol5278/NumPy/blob/master/2d_matrix_indexing_and_slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Create 2d array**

In [0]:
import numpy as np

In [2]:

m = np.array([ [5,10,15], [20,25,30], [35,40,45] ])
print(m)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


Indexing using double bracket notation

In [4]:
# to get the element 10
print(m[0][1])
# to get the element 25
print(m[1][1])

10
25


Indexing using single bracket notation(Recommended)

In [6]:
# to access 10
print(m[0,1])
# to access 45
print(m[2,2])

10
45


Slicing using single bracket notation

In [10]:
# to get the below output as : [[5,10]
#                               [20,25] ]

print(m[:2])
print(m[:2,:2])

[[ 5 10 15]
 [20 25 30]]
[[ 5 10]
 [20 25]]
