<a href="https://colab.research.google.com/github/Tech-Amol5278/NumPy/blob/master/Conditional_selection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np


In [0]:
a = np.arange(1,11)

In [3]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
a>5  # this checks evry elemnt grter than 5 and returs boolean

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [11]:
mask = a > 5
a[mask]


array([ 6,  7,  8,  9, 10])

refer below more examples

In [12]:
a[a>8]

array([ 9, 10])

In [15]:
a[a==4]

array([4])