<a href="https://colab.research.google.com/github/Tech-Amol5278/NumPy/blob/master/Create_Numpy_arrays_using_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy Functions: zeros,ones,eye,diag,randint,rand,randn

In [0]:
import numpy as np

In [7]:
arr = np.zeros(5)
arr # this returns array of 5 zeros 

array([0., 0., 0., 0., 0.])

In [8]:
arr = np.zeros((2,3))  
arr  # this will returns array of zeros with 2 rows and 3 columns

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
arr  = np.ones(5)
arr  # this returns array of 5 zeros 

array([1., 1., 1., 1., 1.])

In [13]:
arr  = np.ones((3,4))
arr  # this will returns array of zeros with 3 rows and 4  columns

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
arr  = np.eye(4) 
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
arr = np.eye(3,4)
arr


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [20]:
arr = np.diag([1,2,3,4])
arr
# this accepts the lits as arguement and create the square matrix using the list elements top left -bottom right diagonally

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [24]:
np.diag(arr) # this is to check diagonal values, refer output of line 23

array([1., 1., 1.])