<a href="https://colab.research.google.com/github/Tech-Amol5278/NumPy/blob/master/Create_Numpy_arrays_using_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy Functions: zeros,ones,eye,diag,randint,rand,randn

In [0]:
import numpy as np

In [0]:
arr = np.zeros(5)
arr # this returns array of 5 zeros 

array([0., 0., 0., 0., 0.])

In [0]:
arr = np.zeros((2,3))  
arr  # this will returns array of zeros with 2 rows and 3 columns

array([[0., 0., 0.],
       [0., 0., 0.]])

In [0]:
arr  = np.ones(5)
arr  # this returns array of 5 zeros 

array([1., 1., 1., 1., 1.])

In [0]:
arr  = np.ones((3,4))
arr  # this will returns array of zeros with 3 rows and 4  columns

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [0]:
arr  = np.eye(4) 
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [0]:
arr = np.eye(3,4)
arr


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [0]:
arr = np.diag([1,2,3,4])
arr
# this accepts the list as arguement and create the square matrix using the list elements top left -bottom right diagonally

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [0]:
np.diag(arr) # this is to check diagonal values, refer output of line 23

array([1, 2, 3, 4])

In [0]:
rand_arr = np.random.randint(1,15,4)  # to get any 4 random numbers between 1 - 15
rand_arr  

array([ 7, 13,  2,  2])

In [0]:
rand_arr = np.random.rand(4)  # to get 4 random numbers from 0 -1 (which is default limit)
rand_arr  

array([0.10639305, 0.44023421, 0.76666151, 0.69692161])

In [0]:
rand_arr = np.random.rand(2,10)  # to get 4 random numbers from 0 -1 (which is default limit)
rand_arr  

array([[0.27287176, 0.46033204, 0.14030654, 0.29986081, 0.24774815,
        0.5307129 , 0.5825482 , 0.40824396, 0.59916418, 0.61896792],
       [0.84685608, 0.372855  , 0.98969917, 0.5051912 , 0.74680673,
        0.88384782, 0.42084914, 0.587411  , 0.57912411, 0.94881752]])

In [0]:
a = np.array([1,2,3,4,5,6,7])
print(a)
print(a.dtype)
print(a.size)   # to get the size of the array
print(a.shape)

[1 2 3 4 5 6 7]
int64
7
(7,)


**arange function**

In [82]:
a = np.arange(100)
print(a)


# this is similar to range function for lists, dictionaries,tuples etc..

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [0]:
a = np.array([[1,2,3,4,5,6,7],[1,2,2,4,5,6,8]])
print(a)
print(a.dtype)
print(a.size)   # to get the size of the array
print(a.shape)  # to get the shape of the array ( 2 rows, 7 cols)

[[1 2 3 4 5 6 7]
 [1 2 2 4 5 6 8]]
int64
14
(2, 7)


In [0]:
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a.reshape(4,2))   # to change the shape (2,4) --> (4,2)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


Slicing on Arrays

In [0]:
a = np.array([(1,2,3,4),(5,6,7,8)])
print(a)
# to get element 3 from a
print(a[0,2])  # 0 : 1st elemnet in the array ie (1,2,3,4),2 : index postion of 3 in (1,2,3,4)

[[1 2 3 4]
 [5 6 7 8]]
3


In [0]:
a = np.array([(1,2,3,4),(5,6,7,8)])
print(a)
# to get (4,8) i.e the last column
print(a[0:,3])
# a[0:] --> remember here the slicing from basic python i.e 0 is the start argument, and no stop arguement means till last element
# 3 --> index postion of last element in the rows i.e 4 and 8
# refer the below example which will clear the doubt incase 

[[1 2 3 4]
 [5 6 7 8]]
[4 8]


In [0]:
a = np.array([(1,2,3,4),(5,6,7,8),(7,8,9,10)])
print(a[0:,3]) # returns [4 8 10] since no stop argument was given
print(a[0:2,3])  # with stop arguement to get only [4 8]


[ 4  8 10]
[4 8]


<h1>Line Spacing</h1>
This gives equally spaced values between the requested nos


In [0]:
a = np.linspace(1,3,5)  # (r1,rn,values)
a
# 5 equal values between 1 and 3

array([1. , 1.5, 2. , 2.5, 3. ])

In [0]:
a = np.linspace(1,3,10)  # (r1,rn,values)
a
# 10 equal values between 1 and 3

array([1.        , 1.22222222, 1.44444444, 1.66666667, 1.88888889,
       2.11111111, 2.33333333, 2.55555556, 2.77777778, 3.        ])

min,max and sum


In [0]:
a = np.array([1,2,3,4])
print(a.min())
print(a.max())
print(a.sum())


1
4
10


In [0]:
a = np.array([(1,2,3,4),(5,6,7,8)])
print(a)
print(a.min())
print(a.max())
print(a.sum())

[[1 2 3 4]
 [5 6 7 8]]
1
8
36


In [0]:
a = np.array([[(1,2,3,4),(5,6,7,8)],[(1,2,3,4),(5,6,7,8)]])
print(a)
print(a.min())
print(a.max())
print(a.sum())

[[[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]]
1
8
72


<h1>Axis</h1>
axis = 0 --> cols
axis = 1 --> rows



In [0]:
a = np.array([(11,2,3),(7,8,9)])
print(a)

print(a.max(axis=0))
print(a.max(axis=1))

print(a.sum(axis=0))
print(a.sum(axis=1))


[[11  2  3]
 [ 7  8  9]]
[11  8  9]
[11  9]
[18 10 12]
[16 24]


<h1>Square root</h1>
Finding squareroots of each element

In [0]:
a = np.array([(11,2,3),(7,8,9)])
print(a)

print(np.sqrt(a))


[[11  2  3]
 [ 7  8  9]]
[[3.31662479 1.41421356 1.73205081]
 [2.64575131 2.82842712 3.        ]]


<h1>Standard Deviation</h1>
Arithmatic steps to get the SD:</br>
1. Work out the Mean (the simple average of the numbers)</br>
2. Then for each number: subtract the Mean and square the result</br>
3. Then work out the mean of those squared differences.</br>
4. Take the square root of that and we are done!</br>


square root of [ (1/N) times Sigma i=1 to N of (xi - mu)^2 ]



In [0]:
a = np.array([(11,2,3),(7,8,9)])
print(a)

print(np.std(a))


[[11  2  3]
 [ 7  8  9]]
3.197221015541813


**add, subtract, multiply and divide**

In [0]:
a = np.array([(11,2,3),(7,8,9)])
b = np.array([(11,2,3),(7,8,9)])

print(a+b)
print(a-b)
print(a*b)
print(a/b)




[[22  4  6]
 [14 16 18]]
[[0 0 0]
 [0 0 0]]
[[121   4   9]
 [ 49  64  81]]
[[1. 1. 1.]
 [1. 1. 1.]]


<h1>Concatenation or Stacking </h1>

  

Vertical stacking

In [0]:
a = np.array([(1,2,3),(4,5,6)])
b = np.array([(7,8,9),(10,11,12)])

print(np.vstack((a,b)))



[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Horizontal stacking


In [0]:
a = np.array([(1,2,3),(4,5,6)])
b = np.array([(7,8,9),(10,11,12)])

print(np.hstack((a,b)))


[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


Converting array to column

In [0]:
a = np.array([(1,2,3),(4,5,6)])

print(a.ravel())

[1 2 3 4 5 6]
