<a href="https://colab.research.google.com/github/Tech-Amol5278/NumPy/blob/master/Reshaping_of_Data_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [23]:
a = np.random.randint(1,100,50)
print(a)
print(a.shape)
print(a.ndim)

[ 7 52 88 65 45 22 31 97 54 68 13 21 94 41  4 97 80 46 47 16 70 52 90 48
 56 45 26 39 69 80 99 36 31 27 37  6 40 77 74 30 30 88 32 28 83 78 28 71
  3 36]
(50,)
1


In [27]:
a = a.reshape(10,5)  # reshaping this to 10 rows,5 cols
print(a)

[[ 7 52 88 65 45]
 [22 31 97 54 68]
 [13 21 94 41  4]
 [97 80 46 47 16]
 [70 52 90 48 56]
 [45 26 39 69 80]
 [99 36 31 27 37]
 [ 6 40 77 74 30]
 [30 88 32 28 83]
 [78 28 71  3 36]]


In [28]:
a = np.random.randint(1,100,50)
print(a)
a = a.reshape(2,5,5)  # reshaping this to 3 dimenstions and 5 values
print(a)

[53 62 62 70 55  9  1 15 44 99  2 65 74 52 25 49 51 49 45 90 91 91 98 55
 20 59 58 35 13 42 27 25 55 98 67 93 19 32 47 24 28 70 36 74 25 10 67 42
 62 58]
[[[53 62 62 70 55]
  [ 9  1 15 44 99]
  [ 2 65 74 52 25]
  [49 51 49 45 90]
  [91 91 98 55 20]]

 [[59 58 35 13 42]
  [27 25 55 98 67]
  [93 19 32 47 24]
  [28 70 36 74 25]
  [10 67 42 62 58]]]


Negative 1 in Reshape

In [29]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
b = a.reshape(2,5)
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [39]:
# same can  be done using -1
# when we give -1, python automatically gets the value, see below..
print(a.size) 

c = a.reshape(2,-1)   
print(c)

# this is same as b, because python replaces the -1 with the expected value, below is the formula
# array size = multiplication of shapes
# i.e 10 = 2 * (-1) # here it replaces -1 with 5




10
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [36]:
d = a.reshape(-1,5)   
print(d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [41]:
e = a.reshape(2,-1)   
print(e)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
