<a href="https://colab.research.google.com/github/Tech-Amol5278/NumPy/blob/master/view_vs_copy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [10]:
a = np.array([5,10,15,20,25,30,35,40])
a

array([ 5, 10, 15, 20, 25, 30, 35, 40])

In [11]:
sliced_a = a[2:5]
print(sliced_a)

[15 20 25]


updating the values in sliced_a or broadcasting

In [12]:
sliced_a[:] = 0
print(sliced_a)

[0 0 0]


In [13]:
# now if we check the our main array, the values inside the main array also has been changed, see below
a
# this is because sliced_a is shares the same memory as a similar to view.

array([ 5, 10,  0,  0,  0, 30, 35, 40])

In [17]:
# to overcome this we can use copy method to create another object.
b = np.array([5,10,15,20,25,30,35,40])

sliced_b = b[2:5].copy()
sliced_b

array([15, 20, 25])

In [21]:
sliced_b[:] = 0
print(sliced_b)
print(b) # see this has not changed the b

[0 0 0]
[ 5 10 15 20 25 30 35 40]
